services:
    # PostgreSQL database
    db:
        container_name: PostgreSQL
        image: postgres:18-alpine
        security_opt:
          # See: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
          - seccomp:unconfined
        volumes:
          - var-lib-postgresql-18:/var/lib/postgresql
          - var-run-postgresql:/var/run/postgresql
        environment:
          - POSTGRES_USER=pynab
          - POSTGRES_PASSWORD=pynab
          - TZ=Europe/Paris
    # Pynab services
    pynab:
        container_name: Pynab
        build:
            context: ..
            dockerfile: Docker/nab/Dockerfile
            args:
              INSTALL_ASSIST: ${PYNAB_DOCKER_INSTALL_ASSIST:-0}
        volumes:
          - ../:/opt/pynab
          - var-run-postgresql:/var/run/postgresql
        depends_on:
          - db
        environment:
          # Include nabassistd here and build with
          # PYNAB_DOCKER_INSTALL_ASSIST=1 when testing Assist Satellite.
          - DAEMONS=${PYNAB_DOCKER_DAEMONS:-nab8balld nabairqualityd nabbookd nabclockd nabmastodond nabsurprised nabtaichid nabweatherd}
          - TZ=Europe/Paris
        command: ["/bin/bash", "/usr/local/bin/run-pynab.sh"]
        ports:
          - ${PYNAB_DOCKER_NABD_PORT:-10543}:10543
          - ${PYNAB_DOCKER_NABD_EVENTS_PORT:-10544}:10544
          - ${PYNAB_DOCKER_NABWEB_PORT:-8000}:8000
volumes:
    # Share the PostgreSQL socket between containers
    var-run-postgresql:
    # Persist the PostgreSQL data across restarts
    var-lib-postgresql-18:
