name: 🧪 Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test_suite:
    name: Run test suite
    runs-on: ubuntu-24.04
    # Service containers
    services:
      postgres:
        image: postgres:18
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        python: ["3.13", "3.14"]

    steps:
      - name: Checkout pynab
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y libasound2-dev libmpg123-dev curl postgresql-client
          python -m pip install --upgrade pip setuptools wheel

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Setup PostgreSQL database
        run: |
          PGPASSWORD=postgres PGHOST=localhost PGPORT=5432 psql -U postgres -d postgres -c "CREATE USER pynab PASSWORD 'pynab'; ALTER ROLE pynab CREATEDB;"

      - name: Fake NTP synchronization
        run: sudo mkdir -p /run/systemd/timesync/ && sudo touch /run/systemd/timesync/synchronized

      - name: Check types with mypy
        run: |
          mypy nab*

      - name: Run test suite with coverage
        run: |
          PGPASSWORD=pynab PGHOST=localhost PGPORT=5432 NABD_HOST=127.0.0.1 coverage run -m pytest --ignore=nabd/tests/asr_test.py --ignore=nabd/tests/nlu_test.py
